networks:
  default:
    external:
      name: dy
services:
  db:
    image: mongo:3
    volumes:
      - .db:/data/db
  locomotive:
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=shopinvader-server.dy
      - VIRTUAL_PORT=3000
      - RAILS_ENV=development
      - STORE_ASSET_IN_S3=false
      - DRAGON_FLY_SECRET=thisISaDEMOkeyNOTsecret
      - LOCOMOTIVE_ENABLE_REGISTRATION=true
    build:
      context: .
      args:
        version: $IMAGE_VERSION
    depends_on:
      - db
    volumes:
      - ./data:/usr/src/app/data
      - ./tmp:/usr/src/app/tmp
      - ./log:/usr/src/app/log
      - ./public/sites:/usr/src/app/public/sites
      - ./public/uploaded_assets:/usr/src/app/public/uploaded_assets
      - ./Rakefile:/usr/src/app/Rakefile
version: '3'
